const DEFAULTS={endpoint:'',workflow:'minimax_h3_lightx2v_v5_15s',key:'',mock:true};
const state={tasks:[{id:'FF-240831-001',name:'夏日气泡水 · 01',prompt:'玻璃杯中的气泡水在阳光下闪闪发光，镜头缓慢推进',resolution:'768p',duration:5,status:'processing',progress:68,time:'刚刚'},{id:'FF-240831-000',name:'夏日气泡水 · 预告',prompt:'清晨露珠落在薄荷叶上，微距镜头，清透自然',resolution:'768p',duration:5,status:'completed',progress:100,time:'12 分钟前'},{id:'FF-240830-014',name:'产品静物 · A 版',prompt:'白色背景上的产品静物，柔和侧光，极简商业摄影',resolution:'480p',duration:5,status:'queued',progress:0,time:'昨天 18:42'}],filter:'all',selected:new Set(),rows:[]};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function loadSettings(){try{return {...DEFAULTS,...JSON.parse(localStorage.getItem('frameflow-settings')||'{}')}}catch{return DEFAULTS}}
let settings=loadSettings();
function addRow(value=''){state.rows.push(value);renderRows()}
function renderRows(){const wrap=$('#promptRows');wrap.innerHTML='';state.rows.forEach((v,i)=>{const row=document.createElement('div');row.className='prompt-row';row.innerHTML=`<span class="row-number">${String(i+1).padStart(2,'0')}</span><input value="${v.replaceAll('"','&quot;')}" placeholder="输入第 ${i+1} 条提示词" /><button class="remove-row" title="删除">×</button>`;row.querySelector('input').addEventListener('input',e=>state.rows[i]=e.target.value);row.querySelector('.remove-row').addEventListener('click',()=>{state.rows.splice(i,1);renderRows()});wrap.appendChild(row)}) ; updateCost()}
function updateCost(){const count=state.rows.filter(Boolean).length||1;$('#costEstimate').textContent=`¥ ${(count*Number($('#duration').value||5)*.02).toFixed(2)}`}
function statusMarkup(t){const labels={processing:'生成中',completed:'已完成',queued:'排队中',failed:'失败'};return `<span class="state ${t.status}"><i></i>${labels[t.status]}</span>${t.status==='processing'?`<div class="progress"><i style="width:${t.progress}%"></i></div>`:''}`}
function renderTasks(){const tbody=$('#taskTable');const filtered=state.tasks.filter(t=>state.filter==='all'||t.status===state.filter);tbody.innerHTML='';filtered.forEach(t=>{const tr=document.createElement('tr');tr.dataset.id=t.id;tr.innerHTML=`<td class="check-col"><input type="checkbox" ${state.selected.has(t.id)?'checked':''} /></td><td><div class="task-name">${t.name}</div><div class="task-id">${t.id} · ${t.prompt}</div></td><td><span class="resolution-tag">${t.resolution}</span></td><td>${t.duration}s</td><td class="progress-cell">${statusMarkup(t)}</td><td>${t.time}</td><td class="row-menu">•••</td>`;tr.querySelector('input').addEventListener('change',e=>{e.target.checked?state.selected.add(t.id):state.selected.delete(t.id);updateSelection()});tbody.appendChild(tr)});$('#taskTotal').textContent=state.tasks.length;$('#emptyState').hidden=filtered.length>0;updateSelection()}
function updateSelection(){const n=state.selected.size;$('#selectedCount').textContent=n;$('#downloadSelected').disabled=!n;$('#selectAll').checked=n>0&&n===state.tasks.filter(t=>state.filter==='all'||t.status===state.filter).length}
async function submitBatch(){const prompt=$('#prompt').value.trim();if(!prompt){$('#prompt').focus();return}const prompts=state.rows.filter(Boolean);if(!prompts.length)prompts.push(prompt);const name=$('#batchName').value||'未命名批次';const created=prompts.map((p,i)=>({id:`FF-${Date.now().toString().slice(-6)}-${String(i+1).padStart(3,'0')}`,name:`${name} · ${String(i+1).padStart(2,'0')}`,prompt:p,resolution:$('#resolution').value,duration:Number($('#duration').value)||5,status:settings.mock?'processing':'queued',progress:settings.mock?8:0,time:'刚刚'}));state.tasks.unshift(...created);renderTasks();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});if(settings.mock){setTimeout(()=>{created.forEach(t=>{t.progress=100;t.status='completed'});renderTasks()},3200);return}for(const task of created){try{const response=await fetch(settings.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${settings.key}`},body:JSON.stringify({prompt:task.prompt,duration:task.duration,resolution:task.resolution,ref_image_0:$('#reference').value.trim()||undefined,workflow_id:settings.workflow})});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json();task.id=data?.data?.task_id||data?.task_id||task.id;task.status='processing';task.progress=20}catch(error){task.status='failed';task.error=error.message}renderTasks()}}
function downloadSelected(){state.selected.forEach(id=>{const t=state.tasks.find(x=>x.id===id);if(!t)return;const blob=new Blob([`FrameFlow demo video\nTask: ${t.id}\nPrompt: ${t.prompt}`],{type:'video/mp4'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${t.name.replaceAll(' ','_')}.mp4`;a.click();URL.revokeObjectURL(a.href)});}
function openSettings(){const s=settings;$('#apiEndpoint').value=s.endpoint;$('#workflowId').value=s.workflow;$('#apiKey').value=s.key;$('#mockMode').checked=s.mock;$('#settingsModal').hidden=false}
function saveSettings(){settings={endpoint:$('#apiEndpoint').value.trim()||DEFAULTS.endpoint,workflow:$('#workflowId').value.trim()||DEFAULTS.workflow,key:$('#apiKey').value.trim(),mock:$('#mockMode').checked};localStorage.setItem('frameflow-settings',JSON.stringify(settings));$('#settingsModal').hidden=true}
document.addEventListener('DOMContentLoaded',()=>{addRow('镜头切入一杯冰镇气泡水，阳光穿过玻璃，商业广告质感');addRow('气泡在杯中升起，背景是夏日泳池，镜头平滑推进');renderTasks();$('#addRow').addEventListener('click',()=>addRow());$('#duration').addEventListener('input',updateCost);$('#submitBatch').addEventListener('click',submitBatch);$('#downloadSelected').addEventListener('click',downloadSelected);$('#openSettings').addEventListener('click',openSettings);$('#closeSettings').addEventListener('click',()=>$('#settingsModal').hidden=true);$('#saveSettings').addEventListener('click',saveSettings);$('#toggleKey').addEventListener('click',()=>{const i=$('#apiKey');i.type=i.type==='password'?'text':'password';$('#toggleKey').textContent=i.type==='password'?'显示':'隐藏'});$('#testConnection').addEventListener('click',()=>{const result=$('#testResult');result.textContent=settings.mock?'演示模式已就绪，无需请求真实 API。':'正在测试连接…';if(!settings.mock)setTimeout(()=>result.textContent='接口地址已保存，可在提交时发起请求。',800)});$('#selectAll').addEventListener('change',e=>{state.tasks.filter(t=>state.filter==='all'||t.status===state.filter).forEach(t=>e.target.checked?state.selected.add(t.id):state.selected.delete(t.id));renderTasks()});$$('.segmented button').forEach(b=>b.addEventListener('click',()=>{$$('.segmented button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.filter=b.dataset.filter;renderTasks()}));$('#clearForm').addEventListener('click',()=>{$('#batchName').value='';$('#prompt').value='';$('#reference').value='';state.rows=[];renderRows()});});
